export const AWS_SWF_NATIVE_CLIENT = Symbol('AWS_SWF_NATIVE_CLIENT');
export const AWS_ADAPTER = Symbol('AWS_ADAPTER');
export const WORKFLOW_CLIENT = Symbol('WORKFLOW_CLIENT');
export const APPLICATION_CONFIGURATION = Symbol('APPLICATION_CONFIGURATION');