export enum WorkflowExecutionStates {
  Created = 'Created',
  CanceledBeforeSent = 'CanceledBeforeSent',
  Sending = 'Sending',
  Sent = 'Sent',
  CancelledAfterSent = 'CancelledAfterSent',
  Started = 'Started',
  CancelStateRequested = 'CancelStateRequested',
  CancelRequested = 'CancelRequested',
  Canceled = 'Canceled',
  CancelFailed = 'CancelFailed',
  CompletedStateRequested = 'CompletedStateRequested',
  Completed = 'Completed',
  CompleteFailed = 'CompleteFailed',
  ExecutionFailedStateRequested = 'ExecutionFailedStateRequested',
  ExecutionFailed = 'ExecutionFailed',
  FailFailed = 'FailFailed',
  TimedOut = 'TimedOut',
  ContinuedAsNew = 'ContinuedAsNew',
  ContinueAsNewFailed = 'ContinueAsNewFailed',
  Terminated = 'Terminated',
}
