export const DECISION_RUN_CONTEXT_ZONE_KEY = 'DECISION_RUN_CONTEXT_ZONE_KEY';
export const ACTIVITY_RUN_CONTEXT_ZONE_KEY = 'ACTIVITY_RUN_CONTEXT_ZONE_KEY';
export const DEFAULT_ACTOR_TASK_LIST = 'default';